# file: roles/docker/tasks/main.yml
---
- name: Get Docker Binary
  get_url: url={{docker_url}}/{{ansible_architecture}}/docker-{{docker_version}} dest=/usr/bin/docker mode=0755

- name: Create Docker group
  group: name={{docker_group}} state=present

- name: Add Vagrant User to Docker group
  user: name={{ansible_ssh_user}} groups={{docker_group}} append=yes

- name: Get Docker-Compose Binary
  get_url: url={{docker_compose_url}}/{{docker_compose_version}}/docker-compose-{{ansible_system}}-{{ansible_architecture}} dest=/usr/bin/docker-compose mode=0755

- include: rhel.yml
  when: ansible_os_family == 'RedHat'
  
- include: debian.yml
  when: ansible_os_family == 'Debian'