---
- name: Docker sysconfig
  template: src=docker.sysconfig.j2 dest=/etc/sysconfig/docker
  notify: restart docker service

- name: Docker Socket service
  template: src=docker.socket.j2 dest=/usr/lib/systemd/system/docker.socket
  notify:
    - reload systemd
    - restart docker socket

- name: Docker service
  template: src=docker.service.j2 dest=/usr/lib/systemd/system/docker.service
  notify:
    - reload systemd
    - restart docker service